DROP TABLE IF EXISTS items, users  CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL ,
    CONSTRAINT email UNIQUE (email),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                                        NOT NULL,
    description VARCHAR(512)                                        NOT NULL,
    available   BOOLEAN                                             NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    owner_id    INT REFERENCES users (id),
    request_id  INT
);



